# Data Check

This python note book contains the functionality to check the data saved for or generated by the contact graspnet, to figure out how can I use them.

In [2]:
import numpy as np

## For the Input Data

### What should be saved

Here the input data of the example file provided by the repo and what I saved to .npy file are compared to verify if the saved data is correct

<img src="https://i.kym-cdn.com/photos/images/newsfeed/002/046/368/3fa" width="300" height="400" />

In [3]:
reader_test_data = np.load("/home/franka/contact_graspnet/test_data/13.npy", allow_pickle=True)
# print(reader_test_data)

The result shows that the depth should be given in meter, but the encoding method of the realsense camera is 16UC1, which means the depth value is given by mm, so the saved cv::Mat should be multipied with 10^(-3)
 
### What I saved:

Depth image:

In [4]:
reader_my_data_depth_image = np.load("/home/franka/contact_graspnet/depth_image_data/data.npy", allow_pickle=True)
# print(reader_my_data_depth_image)

Point cloud:

In [5]:
reader_my_data_point_cloud = np.load("/home/franka/contact_graspnet/point_cloud_data/data.npy", allow_pickle=True)
# print(reader_my_data_point_cloud)

## For Output Data

### Output of Contact GraspNet

The output data are generated in a .npz file, here they are loaded

In [6]:
output_data = np.load("/home/franka/contact_graspnet/results/predictions_data.npz", allow_pickle=True)

pred_grasps_cam = output_data["pred_grasps_cam.npy"].item()[-1]
scores = output_data["scores.npy"].item()[-1]
contact_pts = output_data["contact_pts.npy"].item()[-1]

<img src="https://media.tenor.com/RXyf_3Ud5FAAAAAC/%E8%AE%A9%E6%88%91%E7%9C%8B%E7%9C%8B.gif" width="600" height="350" />

In [7]:
print(pred_grasps_cam)
# print(pred_grasps_cam.size)

[[[ 0.7210274   0.6460514  -0.25047353 -0.02953846]
  [ 0.05986541  0.30204818  0.95141107 -0.02785824]
  [ 0.69031554 -0.7009881   0.17910889  0.91759324]
  [ 0.          0.          0.          1.        ]]

 [[ 0.9527667   0.2937941   0.07694456  0.01292571]
  [-0.05388026 -0.08581914  0.9948527   0.07286325]
  [ 0.2988852  -0.95200837 -0.06593592  1.2714114 ]
  [ 0.          0.          0.          1.        ]]

 [[ 0.94462883  0.3204685   0.0705431  -0.12916169]
  [-0.10069078  0.07847732  0.9918179  -0.04450636]
  [ 0.31231034 -0.9440028   0.10640016  1.4846185 ]
  [ 0.          0.          0.          1.        ]]

 ...

 [[ 0.24917883  0.95475096  0.16235891  0.33662587]
  [-0.86558604  0.14436729  0.47949862  0.22450618]
  [ 0.43436244 -0.2600165   0.8623923   0.9038674 ]
  [ 0.          0.          0.          1.        ]]

 [[ 0.62606585  0.7530798  -0.20226811 -0.01641224]
  [-0.2027426   0.4076807   0.89033246  0.00956006]
  [ 0.75295216 -0.5163984   0.40791634  0.91527116

This should be the transformation between the camera_color_optical_link and the grasp pose

In [10]:
print(scores)
# print(scores.size)

[0.30595443 0.25186378 0.27766675 0.34796402 0.22824506 0.31724536
 0.23534738 0.31334627 0.26815483 0.32175338 0.3260992  0.27759773
 0.2882042  0.24385299 0.2854579  0.28535962 0.5255508  0.36808255
 0.5745039  0.3429787  0.29327875 0.38515568 0.2641898  0.32179186
 0.30059445 0.24234807 0.29487106 0.35994002 0.3921374  0.27634978
 0.30383715 0.35903668 0.3085978  0.30285618 0.38562524 0.31031218
 0.25090757 0.3606106  0.29186517 0.37686786 0.5520788  0.22921588
 0.26941508 0.48613554 0.22670539 0.5065755  0.23189883 0.3251825
 0.35762677 0.22677533 0.34559646 0.27740014 0.3776208  0.26313955
 0.23761377 0.33934602 0.22870015 0.23079017 0.27875298 0.25289583
 0.4323337  0.23887147 0.31429508 0.38302937 0.3273536  0.40579903
 0.3916026  0.30062115 0.45333222 0.36359882 0.28775918 0.48785228
 0.23755983 0.2403962  0.24604699 0.49545482 0.23586881 0.32306838
 0.27884775 0.27515253 0.23663394 0.3374168  0.27953476 0.27421004
 0.25369498 0.43427506 0.4223281  0.22925106 0.2980378  0.28312

In [11]:
print(contact_pts)
# print(contact_pts.size)

[[-5.97334877e-02  7.01609701e-02  9.31999981e-01]
 [ 1.89894941e-02  1.75838038e-01  1.26399994e+00]
 [-1.23743646e-01  5.82475811e-02  1.49500000e+00]
 [-2.30866764e-02  9.25866067e-02  9.40999985e-01]
 [ 3.90302598e-01  1.99582711e-01  1.22200000e+00]
 [-9.67404470e-02  6.08969778e-02  1.56299996e+00]
 [-6.19126037e-02  1.93918332e-01  9.66000021e-01]
 [-3.89246568e-02  1.50817364e-01  9.49000001e-01]
 [ 7.19464326e-04  1.61222085e-01  9.73999977e-01]
 [-6.47887066e-02  9.93253440e-02  9.45999980e-01]
 [ 2.17673089e-02  2.06442356e-01  1.26399994e+00]
 [-1.14271663e-01  5.92995435e-02  1.52199996e+00]
 [ 2.98776384e-03  6.87200725e-02  1.62600005e+00]
 [-6.47202209e-02  1.43941507e-01  9.44999993e-01]
 [-5.43131903e-02  1.66820168e-01  9.63000000e-01]
 [-1.11982219e-01  8.13825279e-02  1.56000006e+00]
 [-1.61519144e-02  1.52406588e-01  9.58999991e-01]
 [-1.27315402e-01  7.91914612e-02  1.51800001e+00]
 [-4.64699939e-02  9.07726586e-02  9.32999969e-01]
 [-9.07331035e-02  7.71115124e-

From the output we noticed that the .size indicates the number of the total elements in the array.

### Potential Usage

Now I have pred_grasp_cam as the transformation matrices of the grasp poses, scores as the qualities of the poses and contact_pts as the contact points of the grasp contact points.

How can I make use of them?

#### Classify the Poses According to Objects

The first task is to classify the grasp poses, i.e., to find out which grasp candidate is for which object.